version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: "redis_redis_example"
    ports:
      - "6379:6379"
    networks:
      - redis_backend_network
  db:
    image: mysql:8.0
    container_name: "mysql_redis_example"
    environment:
      - MYSQL_DATABASE=cities
      - MYSQL_ROOT_PASSWORD=cities_password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
networks:
  redis_backend_network:
    driver: bridge
volumes:
  db: